name: msbuild

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
      - main
  pull_request:

env:
  # We do not need these actually. But its here to remember that is can be done
  SOLUTION_FILE_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: MSBuild restore
      run: msbuild /verbosity:minimal /p:Configuration="Release" /p:Platform="Any CPU" /t:restore
    - name: MSBuild compile
      run: msbuild /verbosity:minimal /p:Configuration="Release" /p:Platform="Any CPU"
